name: form_input
description: Dart package which manages the form input.
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  formz: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  plugin_platform_interface: ^2.1.7